In [1]:
import os
import numpy as np 
import cv2
import torch
import torch.nn as nn
from torchvision import models
from torch.autograd import Variable
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [9]:
def load_list(filename):
    final_list = []
    with open(filename, 'r') as filehandle:
        for line in filehandle:
            currentPlace = line[:-1]
            final_list.append(currentPlace)
    return final_list

In [8]:
def save_list(list_name, filename) : 
    with open(filename, 'w') as filehandle:
        for listitem in list_name:
            filehandle.write('%s\n' % listitem)

In [2]:
def read_images(path, folders):
    images = []
    labels = []
    idx = 0
    for folder in folders:
        for filename in os.listdir(path+folder):
            image = cv2.imread(os.path.join(path+folder, filename))
            if image is not None:
                images.append(image)
                labels.append(idx)
                
        idx += 1
    images = np.array(images)
    labels = np.array(labels)
    return images, labels

def getDescriptors(images, labels, model) : 
    features = []
    image_labels = []
    i = 0

    for image in images : 
        # Re-sizing the image
        image = cv2.normalize(image, None, alpha=0, beta=1, norm_type=cv2.NORM_MINMAX, dtype=cv2.CV_32F)
        image = cv2.resize(image, (224, 224), interpolation=cv2.INTER_AREA)
        image = image.transpose(2, 1, 0)
        image = Variable(torch.Tensor(image))
        image = image.unsqueeze(0)
        feature = model(image)
        feature = feature.data.numpy().reshape(4096)
        if feature is not None : 
            features.append(feature)
            image_labels.append(labels[i])
        i += 1
        print (feature)

    features = np.asarray(features)
    return features, image_labels

In [3]:
model = models.alexnet(pretrained=True)
new_classifier = nn.Sequential(*list(model.classifier.children())[:-1])
model.classifier = new_classifier
model.eval()

AlexNet(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(11, 11), stride=(4, 4), padding=(2, 2))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    (3): Conv2d(64, 192, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
    (4): ReLU(inplace=True)
    (5): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    (6): Conv2d(192, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (7): ReLU(inplace=True)
    (8): Conv2d(384, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (9): ReLU(inplace=True)
    (10): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace=True)
    (12): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (avgpool): AdaptiveAvgPool2d(output_size=(6, 6))
  (classifier): Sequential(
    (0): Dropout(p=0.5, inplace=False)
    (1): Linear(in_features=9216, out_features=4096, bias=True)
 

In [5]:
root = "/home/ananya/Documents/VR/assignments/Group2/Feature-Learning/Part_c/101_ObjectCategories-20200418T064923Z-001/101_ObjectCategories/"

set_images = [ item for item in os.listdir(root) if os.path.isdir(os.path.join(root, item)) ]
images, labels = read_images(root, set_images)

In [11]:
features, image_labels = getDescriptors(images, labels, model)


[0.        0.        1.1785016 ... 0.        0.        4.9072027]
[0. 0. 0. ... 0. 0. 0.]
[0.         0.         0.         ... 0.         0.         0.00551917]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0.        0.        0.        ... 0.        0.        0.8781526]
[0.8363091 0.        0.        ... 0.        0.        1.205776 ]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0.        0.        0.        ... 0.        0.        0.4924363]
[0.        0.        0.        ... 0.        0.        1.9234115]
[0.         0.         0.         ... 0.         0.         0.22703308]
[0.         0.         0.         ... 0.         0.         0.13137788]
[0.        0.        0.        ... 0.        0.        2.0489767]
[5.234216  0.        0.        ... 0.        0.        0.6110293]
[0.        0.        0.        ... 0.        0.        1.3987569]
[0. 0. 0. ... 0. 0. 0.]
[0.         0.         0.49410582 ... 0.

[0.5172821 0.        0.        ... 0.        0.        0.       ]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[6.0742936 0.        0.        ... 0.        0.        0.       ]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[2.9038508 0.        0.        ... 0.        0.        0.       ]
[1.2558657 0.        0.        ... 0.        0.        0.       ]
[0.42220566 0.         0.         ... 0.         0.         0.        ]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0.

[0.15125014 0.         0.         ... 0.         0.         0.        ]
[0.        0.        0.        ... 0.        0.        0.5425252]
[0.         0.         0.         ... 0.         0.         0.27340436]
[0.        0.        0.        ... 0.        0.        4.1426144]
[1.1131141 0.        0.        ... 0.        0.        6.510044 ]
[0.        0.        0.        ... 0.        0.        1.7909178]
[0. 0. 0. ... 0. 0. 0.]
[0.        0.        0.        ... 0.        0.        1.4777988]
[0. 0. 0. ... 0. 0. 0.]
[1.8219242 0.        0.        ... 0.        0.        3.148276 ]
[0.       0.       0.       ... 0.       0.       2.727941]
[0. 0. 0. ... 0. 0. 0.]
[0.       0.       0.306836 ... 0.       0.       0.      ]
[1.6266339 0.        0.        ... 0.        0.        0.       ]
[0.       0.       0.       ... 0.       0.       3.619814]
[0. 0. 0. ... 0. 0. 0.]
[0.         0.         0.         ... 0.         0.         0.09930595]
[0.        0.        0.        ... 0.        0

[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[3.2935126 0.        0.        ... 0.        0.        0.       ]
[0.         0.05306478 0.         ... 0.         0.         0.4674223 ]
[0.25418422 0.         0.         ... 0.         0.         0.        ]
[0.3957679 0.        0.        ... 0.        0.        0.       ]
[0.       0.       0.       ... 0.       0.       1.615702]
[0. 0. 0. ... 0. 0. 0.]
[0.630908 0.       0.       ... 0.       0.       0.      ]
[2.3957937 0.        0.        ... 0.        0.        0.8965951]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0.        0.        0.        ... 0.        0.        1.3177701]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0.         0.         0.         ... 0.         0.         0.10077315]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0.

[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0.       0.       0.       ... 0.       0.       6.565831]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0.         1.0011911  0.         ... 0.         0.         0.90620995]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0.       0.       0.       ... 0.       0.       5.317337]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0.05788879 0.         0.         ... 0.         0.         5.0962834 ]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0.

[5.7566066 0.        0.        ... 0.        0.        0.       ]
[0. 0. 0. ... 0. 0. 0.]
[0.         0.         0.         ... 0.         0.         0.05218273]
[2.9550736 0.        0.        ... 0.        0.        0.       ]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0.5063667 0.        0.        ... 0.        0.        0.       ]
[0. 0. 0. ... 0. 0. 0.]
[4.8243365 0.        0.        ... 0.        0.        0.       ]
[0. 0. 0. ... 0. 0. 0.]
[5.8213716 0.        0.        ... 0.        0.        2.9244635]
[2.445028  0.        0.        ... 0.        0.        1.2753006]
[0.11487325 1.6570759  0.         ... 0.         0.         0.        ]
[0. 0. 0. ... 0. 0. 0.]
[0.39534807 0.25313616 0.         ... 0.         0.         0.        ]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0.7868488 0.        0.        ... 0.        0.        0.       ]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[4.146482 

[3.3933752  0.         0.         ... 0.         0.         0.39916325]
[6.8078375 0.        0.        ... 0.        0.        6.7579927]
[0.        0.        0.        ... 0.        0.        3.4255164]
[4.3410525 0.        0.        ... 0.        0.        0.5055431]
[3.1525104 0.        0.        ... 0.        0.        0.       ]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0.        0.        0.        ... 0.        0.        0.5888432]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0.         0.         0.         ... 0.         0.         0.52672094]
[0. 0. 0. ... 0. 0. 0.]
[0.        3.5584652 0.        ... 0.        0.        0.       ]
[0. 

[3.7587368 0.        0.        ... 0.        0.        0.       ]
[0.        0.        0.0283578 ... 0.        0.        0.       ]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[3.0087028 0.        0.        ... 0.        0.        0.       ]
[0.        0.        0.        ... 0.        0.        0.7537924]
[1.7195549 0.        0.        ... 0.        0.        0.       ]
[3.2575378 0.        0.        ... 0.        0.        0.       ]
[0.       0.       0.       ... 0.       0.       5.082218]
[3.4647837 0.        0.        ... 0.        0.        1.5867771]
[0.435433  0.        0.        ... 0.        0.        0.8734292]
[1.7020197 0.        0.        ... 0.        0.        7.08095  ]
[0.        0.        0.        ... 0.        0.        5.4423437]
[1.9310083 0.        0.        ... 0.        0.        0.8674814]
[0.         0.         0.         ... 0.         0.         0.49484444]
[0.        0.        0.        ... 0.        0

[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0.        0.        0.        ... 0.        0.        1.3516299]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0.        2.8941047 0.        ... 0.        0.        0.       ]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[4.9414887 0.        0.        ... 0.        0.        0.       ]
[0.        0.        0.        ... 0.        0.        1.3140372]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0.        0.        0.6788815 ... 0.        0.        0.       ]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.

[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0.        0.        0.        ... 0.        0.        4.9323177]
[0.         0.         0.25105807 ... 0.         0.         0.        ]
[3.4217477 0.        0.        ... 0.        0.        3.4000773]
[0. 0. 0. ... 0. 0. 0.]
[0.        0.        0.        ... 0.        0.        2.0541842]
[0.       0.       0.       ... 0.       0.       1.801426]
[0.         0.         0.         ... 0.         0.         0.20565331]
[0. 0. 0. ... 0. 0. 0.]
[0.         0.         0.03442471 ... 0.         0.         0.        ]
[0.        0.        0.        ... 0.        0.        2.5697384]
[0.       0.       0.       ... 0.       0.       5.014948]
[0.        0.        0.        ... 0.        0.        2.0080287]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0.        0.        0.        ... 0.        0.        2.1300693]
[0. 0. 0. ... 0. 0. 0.]
[2.326848  0.        0.     

[0.       0.       0.       ... 0.       0.       2.147629]
[0.        0.        0.        ... 0.        0.        3.8406196]
[0.21792327 0.         0.         ... 0.         0.         2.6966767 ]
[0.        0.        0.        ... 0.        0.        2.3133712]
[0.        0.        0.        ... 0.        0.        1.1439325]
[0.        0.        0.        ... 0.        0.        2.1646216]
[0.        0.        0.        ... 0.        0.        3.5292768]
[0.        0.        0.        ... 0.        0.        2.7558095]
[0.        0.        0.        ... 0.        0.        2.5934968]
[0.        0.        0.        ... 0.        0.        2.2469392]
[0.        0.        0.        ... 0.        0.        1.0670352]
[0.        0.        0.        ... 0.        0.        0.9348531]
[0.         0.         0.         ... 0.         0.         0.67235184]
[0.        0.        0.        ... 0.        0.        0.8488999]
[0.        0.        0.        ... 0.        0.        2.1205955]
[0. 

In [12]:
save_list(features,"features.txt")
save_list(image_labels,"labels.txt")

In [13]:
pca = PCA(n_components = 0.9) 
features = pca.fit_transform(features) 
print(features)

[[ 7.7248545e+00  1.5292032e+01  2.1356050e+01 ...  1.0671784e+00
   2.9426563e-01 -7.2578567e-01]
 [-7.1923089e+00  5.2931943e+00  2.4525600e+01 ... -5.9125453e-01
   6.4452104e-02  5.8367508e-03]
 [-1.8098685e+00  1.8704668e+01 -3.3062434e+00 ... -2.1030644e-01
  -1.2258154e+00 -1.3614107e+00]
 ...
 [ 1.4859148e+01 -1.4180125e+01 -7.8913836e+00 ... -5.4758006e-01
   8.6180918e-02 -3.5980761e-02]
 [ 5.5217242e+00 -5.5589037e+00  3.3867088e+01 ... -4.6013057e-01
   9.7820693e-01 -1.6546230e+00]
 [-1.3319204e+01  6.5904145e+00 -4.8447566e+00 ... -5.8490419e-01
  -6.6882655e-02 -1.1268005e+00]]


In [14]:
x_train, x_test, y_train, y_test = train_test_split(features, 
                                                    image_labels, 
                                                    test_size=0.1, 
                                                    random_state=4)


In [15]:
clf = cv2.ml.KNearest_create()
clf.train(x_train, cv2.ml.ROW_SAMPLE, np.asarray(y_train, dtype=np.float32))

True

In [16]:
ret, results, neighbours ,dist = clf.findNearest(x_test, k=10)

In [17]:
pred_label = []
correct_label = []

for label in results:
    pred_label.append(int(label))

for label in y_test:
    correct_label.append(int(label))

print (y_test)
print (pred_label)

print (len(pred_label))
print (len(correct_label))
    
accuracy_score(y_test, pred_label)

[53, 1, 27, 20, 53, 65, 62, 23, 41, 6, 65, 6, 6, 1, 48, 56, 5, 58, 23, 15, 17, 21, 65, 9, 59, 50, 6, 74, 40, 59, 35, 32, 59, 64, 10, 7, 7, 21, 9, 46, 6, 12, 50, 34, 58, 7, 38, 30, 46, 10, 30, 57, 22, 12, 59, 30, 65, 29, 1, 67, 65, 16, 34, 56, 6, 64, 62, 6, 74, 17, 9, 63, 40, 6, 27, 63, 30, 27, 7, 27, 74, 27, 12, 51, 34, 67, 65, 56, 9, 0, 74, 63, 48, 10, 38, 58, 22, 58, 62, 74, 50, 59, 9, 40, 6, 17, 56, 7, 34, 53, 52, 27, 68, 17, 5, 51, 65, 51, 6, 10, 10, 22, 42, 30, 65, 51, 40, 10, 11, 23, 30, 6, 11, 27, 51, 22, 59, 3, 23, 53, 62, 51, 48, 50, 56, 63, 11, 65, 49, 7, 40, 75, 9, 50, 61, 48, 16, 53, 36, 68, 6, 52, 6, 58, 11, 9, 63, 8, 37, 40, 23, 20, 10, 6, 74, 76, 3, 67, 6, 68, 49, 20, 7, 64, 48, 59, 65, 53, 49, 51, 17, 10, 11, 56, 75, 51, 7, 48, 65, 17, 56, 16, 32, 20, 48, 56, 67, 0, 65, 8, 12, 51, 38, 74, 56, 49, 48, 53, 76, 49, 38, 11, 51, 75, 46, 27, 74]
[53, 1, 12, 20, 53, 65, 62, 23, 41, 6, 15, 17, 6, 1, 1, 20, 9, 58, 27, 15, 59, 21, 73, 27, 59, 50, 6, 74, 40, 11, 15, 15, 59, 64, 34

0.6519823788546255